### ISSUE TITLE
cannot import converters

### ISSUE THREAD

**Issue by Surya-Upadhyayula** [alubbock/thunor#13]
Hi Team,

I have been experimenting with your package and wanted to use converters to import and convert external datasets. When I am issuing the statement
from thunor.converters import convert_ctrp
module not found error is issued.
I can see that in the installed package tree, within the converters folder you have 3 converters scripts. And the function call should go through these modules. 
Could you help in fixing it and making it work ?
Thanks
Dr. Raghavender

**Comment by alubbock** [comment]
Hi,

This has been fixed in the latest version, v0.1.29.

Please upgrade with `pip install --upgrade thunor` and you should be able to import the converters.

Thanks,
Alex

**Comment by Surya-Upadhyayula** [comment]
Thanks. It is fixed.
