### ISSUE TITLE
Trying out on my own data

### ISSUE THREAD

**Issue by ad05bzag** [alubbock/thunor#6]
Hey, could you please give me some pointers on how to format an input csv (or create an h5 file), so that i can test out thunor. 

I would have a simple case where i have a dataframe with doses and cell count for control/drug. I am using python

**Comment by alubbock** [comment]
Hi, the easiest way to get data in is to use a CSV file. The column names and requirements are described here: https://docs.thunor.net/create-a-dataset. The [Thunor tutorial](http://core.thunor.net/en/latest/) contains a worked example of how to load data in.

If you want example data, there's an [HDF5-format example file included with Thunor](https://github.com/alubbock/thunor/blob/master/thunor/testdata/hts007.h5). You can convert the HDF5 format to CSV like this:

    import thunor.io
    dataset = thunor.io.read_hdf('file.h5')
    thunor.io.write_vanderbilt_hts(dataset, 'file.csv')

In addition to the Thunor Python package (this Github repository, also called Thunor Core), there's also a [web interface](https://docs.thunor.net/), which includes a [graphical plate mapper](https://demo.thunor.net/platemap) among other features, in case your data need annotating (labeling with cell lines, drugs, and concentrations in each well).

Hope that helps! Please let me know if you have any further questions.
